### ISSUE TITLE
keyboard support

### ISSUE THREAD

**Issue by jbrokamp** [plbrault/youre-the-os#63]
Thank you for making a creative and fun game.

It could be nice to have some key bindings, like:
- numeric keys could correspond to the CPU no
- i/o event button bound to some other key

i'm not sure what would be a good way to bind the processes, however.

**Comment by smiba** [comment]
I feel like if this game got keyboard support we could start to see some real intense gameplay

**Comment by plbrault** [comment]
Mapping the I/O event button to a key (I'm thinking the spacebar) would be the easiest.

As for mapping numeric keys to CPU's, the only problem I see is that the game allows up to 16 CPU's.

**Comment by plbrault** [comment]
Using SHIFT for CPU's 9-16 is an interesting idea!

As for using WASD for selecting idle processes, I also thought about it but I'm not sure how that would be more efficient than using the mouse.

**Comment by plbrault** [comment]
Key bindings are now implemented.

For now, CPUs 1-9 are mapped to keys 1-9, CPU 10 is mapped to key 0, and CPUS 11-16 are mapped to Shift+1-6. I did not put CPUs on 2 rows as suggested because that would require reworking the whole interface, and I'm not sure a lot of people play the game with so many CPUs.

**Comment by wviana** [comment]
This feature was awesome. Got even cooler to play this
